name: draw_cloud
description: "DrawCloud - A Flutter drawing and gallery app with Firebase integration."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.1.6
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  get_it: 7.7.0
  injectable: 2.4.4
  # firebase_core: 3.8.1
  # firebase_auth: 5.3.4
  # cloud_firestore: 5.5.1
  go_router: 14.6.2
  dartz: 0.10.1
  equatable: 2.0.7
  connectivity_plus: 6.1.1
  flutter_svg: 2.0.14
  image_picker: 1.1.2
  image_gallery_saver_plus: 3.0.5
  cached_network_image: 3.4.1
  share_plus: 10.1.4
  flutter_local_notifications: 18.0.1
  permission_handler: 11.3.1
  path_provider: 2.1.5
  shimmer: 3.0.0
  flutter_native_splash: 2.4.3
  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.12
  freezed: 2.5.2
  json_serializable: 6.8.0
  injectable_generator: 2.6.2
  flutter_lints: 5.0.0
  mocktail: 1.0.4
  bloc_test: 9.1.7
  flutter_gen_runner: 5.5.0+1
  flutter_launcher_icons: 0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-logo.png"
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/app-logo.png"
  remove_alpha_ios: true

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
